---
# https://discussions.apple.com/thread/8200117
- name: Disable Spotlight
  command: |
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

# http://osxdaily.com/2015/02/03/set-or-disable-sleep-due-to-mac-system-inactivity-from-the-command-line-in-os-x/
- name: Disable system sleep
  command: |
    systemsetup -setcomputersleep Never

# https://discussions.apple.com/thread/7610386
- name: Disable screen saver
  command: |
    sudo -u {{application_user}} defaults -currentHost write com.apple.screensaver idleTime 0

- name: Retrieve installer for git
  get_url:
    url: https://svwh.dl.sourceforge.net/project/git-osx-installer/git-2.17.0-intel-universal-mavericks.dmg
    dest: ~/git.dmg
  register: download_git

- name: Install git
  shell: |
    #!/bin/bash
    set -x

    hdiutil mount ~/git.dmg

    installer \
      -package '/Volumes/Git 2.17.0 Mavericks Intel Universal/git-2.17.0-intel-universal-mavericks.pkg' \
      -target '/Volumes/Macintosh HD'

    hdiutil unmount '/Volumes/Git 2.17.0 Mavericks Intel Universal/'
  when: download_git.changed
