---
# In Ubuntu 16.04, open file limits are set via two independent configuration
# files.
#
# https://ro-che.info/articles/2017-03-26-increase-open-files-limit
- name: Raise limit on number of open files (systemd settings)
  lineinfile: dest=/etc/systemd/system.conf
    regexp="DefaultLimitNOFILE"
    line="DefaultLimitNOFILE=65536"
    state=present

- name: Raise limits on number of open files (PAM settings)
  lineinfile:
    dest: /etc/security/limits.conf
    line: '{{item}}'
  with_items:
    - '* soft nofile 65536'
    - '* hard nofile 65536'

- name: Create directory to store downloaded files
  file:
    name: ~/downloads
    state: directory

- name: Download Sauce Connect
  get_url:
    url: https://saucelabs.com/downloads/sc-4.5.0-linux.tar.gz
    dest: ~/downloads
    checksum: sha1:06e52acbbde3668a8effbf0dc970b40e32763fa6

- name: Unpack Sauce Connect
  unarchive:
    src: ~/downloads/sc-4.5.0-linux.tar.gz
    dest: ~/downloads
    creates: ~/downloads/sc-4.5.0-linux/bin/sc
    remote_src: true

- name: Install Sauce Connect
  copy:
    src: ~/downloads/sc-4.5.0-linux/bin/sc
    dest: /usr/local/bin
    mode: 0755
    remote_src: true

- name: Install wrapper for Sauce Connect
  copy:
    src: files/sc-wrapper
    dest: /usr/local/bin
    mode: 0755

- name: Create directory to store log files
  file:
    name: /var/log/sauce-connect
    owner: '{{application_user}}'
    group: '{{application_group}}'
    state: directory

- name: Configure log file rotation
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/sauce-connect
