---
- hosts: all
  #remote_user: username specified in /etc/ansible/hosts
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
    - vars/vault
  tasks:
  - name: Set authorized key, removing all the authorized key already set
    authorized_key:
     user: root
     key: '{{ item }}'
     state: present
     exclusive: True
    with_file:
     - public_keys/web-platform

  - name: Create directory to store keys
    file:
      name: /root/keys
      state: directory

  - name: Download keys for external package repositories
    get_url:
      url: '{{item.key_url}}'
      dest: /root/keys/{{item.name}}
    with_items: '{{external_packages}}'

  - name: Install keys for external package repositories
    command: apt-key add /root/keys/{{item.name}}
    with_items: '{{external_packages}}'

  - name: Add apt sources
    lineinfile:
      dest: '/etc/apt/sources.list.d/{{item.name}}.list'
      line: '{{item.repository}}'
      create: true
    with_items: '{{external_packages}}'

  - name: update package repository
    command: apt-get update

  - name: Infer current kernel Linux version
    command: uname -r
    register: kernel_version

  - name: Install kernel Linux headers
    apt:
      name: linux-headers-{{kernel_version.stdout}}
      state: present
    notify: Restart system

  - name: install the various packages we need
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - curl
      - dtrx
      - emacs-nox
      - firefox
      - git
      - google-chrome-stable
      - google-cloud-sdk
      - htop
      - libnss3-tools
      - nvidia-367
      - nvidia-375
      - nvidia-384
      - python-pip
      - python2.7
      - rsync
      - screen
      - unattended-upgrades
      - virtualenv
      - xauth
      - xvfb

  - name: Create directory to store downloaded files
    file:
      name: ~/downloads
      state: directory

  - name: Download Mozilla Geckodriver
    get_url:
      url: https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
      dest: ~/downloads/

  - name: Install Mozilla Geckodriver
    unarchive:
      src: ~/downloads/geckodriver-v0.19.1-linux64.tar.gz
      dest: /usr/local/bin
      remote_src: true

  - name: Download Google Chromedriver
    get_url:
      url: https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
      dest: ~/downloads/

  - name: Install Google Chromedriver
    unarchive:
      src: ~/downloads/chromedriver_linux64.zip
      dest: /usr/local/bin
      remote_src: true

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: make sure we can open enough files
    lineinfile: dest=/etc/systemd/system.conf
      regexp="DefaultLimitNOFILE"
      line="DefaultLimitNOFILE=65536"
      state=present

  - name: Create group
    group:
      name: '{{application_group}}'
      state: present
      system: true

  - name: Create user account
    user:
      name: '{{application_user}}'
      state: present
      system: true
      shell: /bin/bash

  - name: checkout the wptdashboard project
    git:
      repo: 'https://github.com/w3c/wptdashboard.git'
      dest: /home/{{application_user}}/wptdashboard
      force: yes

  - name: checkout the web-platform-tests
    git:
      repo: 'https://github.com/w3c/web-platform-tests.git'
      dest: /home/{{application_user}}/web-platform-tests
      force: yes

  - name: make python virtualenv
    pip:
      name: virtualenv
      virtualenv: /home/{{application_user}}/web-platform-tests/_venv

  - name: Grant file ownership to application user
    file:
      path: '{{item}}'
      group: '{{application_group}}'
      owner: '{{application_user}}'
      state: directory
      recurse: true
    with_items:
      - /home/{{application_user}}/wptdashboard
      - /home/{{application_user}}/web-platform-tests

  - name: install python requirements
    pip:
      requirements: /home/{{application_user}}/wptdashboard/requirements.txt

  - name: ensure we have the latest google-sdk
    command: pip install --upgrade google-cloud
    async: 0
    poll: 0
    ignore_errors: true

  # This file was generated by creating a Google Cloud "service account" via
  # the Google Cloud Platform console as per the instructions here:
  #
  # https://cloud.google.com/docs/authentication/getting-started
  - name: Copy Google Cloud Platform service account credentials into place
    copy:
      src: files/google-cloud-platform-credentials.json.encrypted
      dest: /home/{{application_user}}/google-cloud-platform-credentials.json
      owner: '{{application_user}}'
      group: '{{application_group}}'
      mode: 0400

  - name: Activate Google Cloud Platform service account credentials
    lineinfile:
      path: /home/{{application_user}}/.bash_profile
      line: export GOOGLE_APPLICATION_CREDENTIALS=/home/{{application_user}}/google-cloud-platform-credentials.json
      create: true
      owner: '{{application_user}}'
      group: '{{application_group}}'

  - name: Copy browser runner script into place
    template:
      src: files/browser-runner.sh
      dest: /home/{{application_user}}/browser-runner.sh
      owner: '{{application_user}}'
      group: '{{application_group}}'
      mode: 0755

  - name: make a cronjob to run browser-runner.sh
    cron:
      name: "run browsers"
      minute: "*/1"
      job: "/home/{{application_user}}/browser-runner.sh > /home/{{application_user}}/browser-runner.log 2>&1"
      user: '{{application_user}}'

  - name: make a cronjob to remove browser-running.txt at boot
    cron:
      name: "a job for reboot"
      special_time: reboot
      job: "rm /home/{{application_user}}/browser-running.txt"
      user: '{{application_user}}'

  - name: put the running.ini file in place
    template:
      src: files/running.ini.j2
      dest: /home/{{application_user}}/wptdashboard/run/running.ini
      group: '{{application_group}}'
      owner: '{{application_user}}'
      mode: 0755

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
    - name: Restart system
      command: /sbin/shutdown -r +1
