---
- name: Copy user automation script into place
  template:
      src: start-buildbot-worker.applescript.j2
      dest: /Users/{{application_user}}/start-buildbot-worker.applescript

- name: Define a system service
  template:
    src: start.buildbot.worker.plist.j2
    dest: /Library/LaunchDaemons/start.buildbot.worker.plist

- name: Enable the system service
  command: launchctl load -w /Library/LaunchDaemons/start.buildbot.worker.plist

- name: Enable operating system automation (requires manual intervention)
  shell: |
    #!/bin/bash
    set -e
    echo '
      set prompt to "UI element scripting is not enabled. Please allow the Terminal application to control your computer.\nThis script will pause until enabled."
      tell application "System Events"
          if UI elements enabled then
              return
          end if
          tell application "System Preferences"
              activate
              set current pane to pane "com.apple.preference.security"
                  log prompt
              display dialog prompt
          end tell

          repeat while not (UI elements enabled)
              delay 1
          end repeat
      end tell
    ' | osascript -

- name: Install script for enabling remote automation in Safari
  copy:
    src: ../../src/scripts/safari-enable-automation.sh
    dest: /usr/local/bin/
    mode: 0755

# https://discussions.apple.com/thread/8200117
- name: Disable Spotlight
  command: |
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

- name: Disable system sleep
  command: '{{item}}'
  with_items:
    # This first command likely subsumes those that follow, however, they are all
    # executed because the available documentation does not make this claim.
    - systemsetup -setsleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
    - systemsetup -setharddisksleep Never

- name: Restart after power failures
  command: systemsetup setrestartpowerfailure on

# https://discussions.apple.com/thread/7610386
- name: Disable screen saver
  command: |
    sudo -u {{application_user}} defaults -currentHost write com.apple.screensaver idleTime 0

- name: Retrieve installer for git
  get_url:
    url: https://svwh.dl.sourceforge.net/project/git-osx-installer/git-2.17.0-intel-universal-mavericks.dmg
    dest: ~/git.dmg
  register: download_git

- name: Install git
  shell: |
    #!/bin/bash
    set -x

    hdiutil mount ~/git.dmg

    installer \
      -package '/Volumes/Git 2.17.0 Mavericks Intel Universal/git-2.17.0-intel-universal-mavericks.pkg' \
      -target '/Volumes/Macintosh HD'

    hdiutil unmount '/Volumes/Git 2.17.0 Mavericks Intel Universal/'
  when: download_git.changed

- name: Install script for managing SSL certificates
  copy:
    src:  ../../src/scripts/trust-root-ca.sh
    dest: /usr/local/bin/
    mode: 0755

# This allows workers to trust cerfificate via `sudo trust-root-ca.sh`
- name: Allow application user to trust root certificates
  lineinfile:
    dest: /etc/sudoers
    line: '{{application_user}} ALL=(ALL) NOPASSWD: /usr/local/bin/trust-root-ca.sh'
