---
- name: Copy Python requirements file into place
  copy:
    src: requirements.txt
    dest: '{{home_dir}}'

- name: Install Python dependencies
  pip:
    requirements: '{{home_dir}}/requirements.txt'
    # macOS version 10.13 includes Python packages which conflict with the
    # project requirements. Ignore those packages during installation.
    extra_args: --ignore-installed

- name: Create a Buildbot worker
  command: |
    sudo --user {{application_user}}
        buildbot-worker create-worker
          --allow-shutdown file
          {{home_dir}}/worker {{master_hostname}} {{application_user}} {{buildbot_worker_password}}
  args:
    chdir: '{{home_dir}}'
    creates: '{{home_dir}}/worker'

- include_tasks: unattended_upgrades.yml

- name: Insert description of worker system
  template:
    src: host.j2
    owner: '{{application_user}}'
    group: '{{application_group}}'
    dest: '{{home_dir}}/worker/info/host'
  notify:
    - Restart "build worker" service

- name: Install script for clearing ports
  copy:
    src: ../../src/scripts/kill-by-port.sh
    dest: /usr/local/bin/kill-by-port.sh
    mode: 0755

- name: Install script for running WPT
  copy:
    src: ../../src/scripts/run-and-verify.py
    dest: /usr/local/bin/run-and-verify.py
    mode: 0755

- name: Install scripts for managing browser binaries
  copy:
    src: '{{item}}'
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - ../../src/scripts/install-browser.sh
    - ../../src/scripts/install-webdriver.sh
    - ../../src/scripts/read-browser-version.py

# This allows workers to edit install web browsers via `sudo install-browser.sh`
- name: Allow application user to install web browsers
  lineinfile:
    dest: /etc/sudoers
    line: '{{application_user}} ALL=(ALL) NOPASSWD: /usr/local/bin/install-browser.sh'
